version: '2.1'

services:
  zookeeper-1:
    image: zookeeper:3.4.9
    hostname: zookeeper-1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper-1:2888:3888
    volumes:
      - ./broker/zookeeper-1/data:/data
      - ./broker/zookeeper-1/datalog:/datalog

  kafka-1:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./broker/kafka-1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper-1

  fuseki-1:
    image: stain/jena-fuseki
    hostname: fuseki-1
    ports:
    - "3030:3030"
    volumes:
    - ./triplestore/fuseki-1:/fuseki
    environment:
      ADMIN_PASSWORD: secret

  rdf4j-workbench-1:
    image: yyz1989/rdf4j
    hostname: rdf4j-workbench-1
    ports:
      - "8080:8080"
    volumes:
      - ./rdf4j/workbench-1/:/data
    environment:
      RDF4J_DATA: /data

